In [2]:
!unzip "/content/Lab1 - Ciencia de Dados.zip"

Archive:  /content/Lab1 - Ciencia de Dados.zip
  inflating: relatorio_exemploFulano.csv
  inflating: relatorio_seunome.csv
  inflating: pandas_tarefa.ipynb
  inflating: oscars.csv
  inflating: imdb.csv
  inflating: __MACOSX/._imdb.csv

In [7]:
import pandas as pd

csv = pd.read_csv("imdb.csv")

df = pd.DataFrame(csv)

In [18]:
df.head()
df.info()
# df.describe()
# df.isnull()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7536 entries, 0 to 7535
Data columns (total 39 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   7536 non-null   object
 1   title                7536 non-null   object
 2   link                 7536 non-null   object
 3   year                 7536 non-null   int64
 4   duration             7525 non-null   object
 5   ratingmpa            7172 non-null   object
 6   ratingimdb           7536 non-null   float64
 7   vote                 7536 non-null   int64
 8   budget               5465 non-null   float64
 9   grossworldwide       5901 non-null   float64
 10  grossuscanada        5661 non-null   float64
 11  grossopeningweekend  4835 non-null   float64
 12  director             7361 non-null   object
 13  writer               7246 non-null   object
 14  star                 7357 non-null   object
 15  genre                7367 non-null   object
 16  countryorigin        7356 non-null   object
 17  filminglocation      6910 non-null   object
 18  productioncompany    7318 non-null   object
 19  language             7349 non-null   object
 20  win                  7536 non-null   int64
 21  nomination           7536 non-null   int64
 22  oscar                7536 non-null   int64
 23  hours                7536 non-null   int64
 24  minutes              7536 non-null   int64
 25  duration_min         7536 non-null   int64
 26  Ceremony             7536 non-null   int64
 27  Year                 7536 non-null   object
 28  Class                7536 non-null   object
 29  CanonicalCategory    7536 non-null   object
 30  Category             7536 non-null   object
 31  FilmId               7536 non-null   object
 32  Name                 7522 non-null   object
 33  Nominees             7240 non-null   object
 34  NomineeIds           7240 non-null   object
 35  Winner               1648 non-null   object
 36  Detail               1940 non-null   object
 37  Note                 79 non-null     object
 38  Citation             14 non-null     object
dtypes: float64(5), int64(9), object(25)
memory usage: 2.2+ MB

In [12]:
import numpy as np
import pandas as pd

df[['hours', 'minutes']] = df['duration'].str.extract(r'(?:(\d+)\s*h)?\s*(?:(\d+)\s*m)?')
df = df.fillna({'hours': 0, 'minutes': 0})
df[['hours','minutes']] = df[['hours','minutes']].astype(int)
df['duration_min'] = df['hours'] * 60 + df['minutes']

# Fill missing values in 'vote' column with 0 before converting to int
df['vote'] = df['vote'].fillna(0).astype(int)

df = df.rename(
    columns={
        'rating_mpa': 'ratingmpa',
        'rating_imdb': 'ratingimdb',
        'gross_world_wide': 'grossworldwide',
        'gross_us_canada': 'grossuscanada',
        'gross_opening_weekend': 'grossopeningweekend',
        'country_origin': 'countryorigin',
        'filming_location': 'filminglocation',
        'production_company': 'productioncompany'
    }
)

df.head()

,id,title,link,year,duration,ratingmpa,ratingimdb,vote,budget,grossworldwide,...,countryorigin,filminglocation,productioncompany,language,win,nomination,oscar,hours,minutes,duration_min
0,tt0073470,Strip Nude for Your Killer,https://www.imdb.com/title/tt0073470,1975,1h 38m,Not Rated,5.6,33000,NaN,NaN,...,Italy,"Milan, Lombardia, Italy",FRAL Cinematografica,Italian,0,0,0,1,38,98
1,tt0072764,Carry on Behind,https://www.imdb.com/title/tt0072764,1975,1h 30m,Not Rated,5.6,31000,NaN,NaN,...,United Kingdom,"Bad Godesberg Way, Maidenhead, Berkshire, Engl...","The Rank Organisation, Peter Rogers Productions",English,0,0,0,1,30,90
2,tt0131526,"So Young, So Lovely, So Vicious...",https://www.imdb.com/title/tt0131526,1975,1h 30m,NaN,4.9,487,NaN,NaN,...,Italy,"Sardinia, Italy",Domiziana Internazionale Cinematografica,Italian,0,0,0,1,30,90
3,tt0073335,Mahogany,https://www.imdb.com/title/tt0073335,1975,1h 49m,PG,6.1,23000,NaN,NaN,...,United States,Marshall Field Co Department Store 111 N Sta...,"Motown Productions, Nikor Productions, Paramou...","English, Italian",0,0,1,1,49,109
4,tt0073006,Foreplay,https://www.imdb.com/title/tt0073006,1975,1h 15m,R,4.0,185,NaN,NaN,...,United States,NaN,SynFrank Enterprises,English,0,0,0,1,15,75

In [13]:
print('5 maiores imdb:')
print(df['ratingimdb'].nlargest(5), end='\n\n')

print('média de duração por decada:')
i = 1960
while(i < 2015):
  mean_movie = df[(df['year'] >= i) & (df['year'] < i+10)]['duration_min'].mean()
  print(f'{mean_movie:.2f}')
  i+=10

print('diretor com maior média IMDb e com no mínimo 3 filmes')
director_stats = df.groupby('director').agg(
    mean_rating=('ratingimdb', 'mean'),
    movie_count=('ratingimdb', 'count')
)
director_stats = director_stats[director_stats['movie_count'] >= 3]
print(director_stats.nlargest(1, 'mean_rating'))

print('genero mais recorrente')
genre_stats = df.groupby('genre').size().sort_values(ascending=False)
print(genre_stats.nlargest(1))

5 maiores imdb:
11166    9.6
20986    9.6
12225    9.5
14532    9.5
11363    9.4
Name: ratingimdb, dtype: float64

média de duração por decada:
98.41
99.53
100.83
103.24
103.58
106.45
diretor com maior média IMDb e com no mínimo 3 filmes
           mean_rating  movie_count
director
Jim Brown     8.633333            3
genero mais recorrente
genre
Drama    2928
dtype: int64

In [14]:
oscars = pd.read_csv("oscars.csv", sep="\t")
oscars_df = pd.DataFrame(oscars)
oscars_df = oscars_df.rename(columns={
    "Film": "title"
})
oscars_df.head()

,Ceremony,Year,Class,CanonicalCategory,Category,title,FilmId,Name,Nominees,NomineeIds,Winner,Detail,Note,Citation
0,1,1927/28,Acting,ACTOR IN A LEADING ROLE,ACTOR,The Noose|The Patent Leather Kid,tt0019217|tt0018253,Richard Barthelmess,Richard Barthelmess,nm0001932,NaN,Nickie Elkins|The Patent Leather Kid,NaN,NaN
1,1,1927/28,Acting,ACTOR IN A LEADING ROLE,ACTOR,The Last Command|The Way of All Flesh,tt0019071|tt0019553,Emil Jannings,Emil Jannings,nm0417837,True,General Dolgorucki [Grand Duke Sergius Alexand...,NaN,NaN
2,1,1927/28,Acting,ACTRESS IN A LEADING ROLE,ACTRESS,A Ship Comes In,tt0018389,Louise Dresser,Louise Dresser,nm0237571,NaN,Mrs. Pleznik,NaN,NaN
3,1,1927/28,Acting,ACTRESS IN A LEADING ROLE,ACTRESS,7th Heaven|Street Angel|Sunrise,tt0018379|tt0019429|tt0018455,Janet Gaynor,Janet Gaynor,nm0310980,True,Diane|Angela|The Wife,NaN,NaN
4,1,1927/28,Acting,ACTRESS IN A LEADING ROLE,ACTRESS,Sadie Thompson,tt0019344,Gloria Swanson,Gloria Swanson,nm0841797,NaN,Sadie Thompson,NaN,NaN

In [15]:
df = pd.merge(df, oscars_df, how="inner", on="title")

In [16]:
best_pictures = df[(df['Category'] == 'BEST PICTURE') & (df['Winner'] == True)]

winner_stats = best_pictures.groupby('director').size().reset_index(name="wins")

most_wins_director = winner_stats.nlargest(1, columns='wins')

print(most_wins_director)

          director  wins
11  Clint Eastwood     2

In [26]:
df['decade'] = (df['year'] // 10) * 10
table = pd.pivot_table(df, values='ratingimdb', index=['decade', 'countryorigin'], aggfunc='mean')

In [31]:
table

                                                           ratingimdb
decade countryorigin
1960   Canada                                                   5.800
       Czechoslovakia                                           7.875
       Czechoslovakia, Italy                                    7.400
       Denmark                                                  7.500
       Denmark, Norway, Sweden                                  7.700
...                                                               ...
2020   United States, United Kingdom, Hungary                   7.700
       United States, United Kingdom, India                     7.700
       United States, United Kingdom, Israel, Greece            6.700
       United States, United Kingdom, Japan                     7.900
       United States, United Kingdom, Morocco, Canada,...       6.700

[784 rows x 1 columns]

In [33]:
pd.melt(df, value_vars=['grossworldwide', 'grossuscanada', 'grossopeningweekend'])

                  variable       value
0           grossworldwide         NaN
1           grossworldwide  41687243.0
2           grossworldwide         NaN
3           grossworldwide         NaN
4           grossworldwide         NaN
...                    ...         ...
22603  grossopeningweekend  20348017.0
22604  grossopeningweekend  20348017.0
22605  grossopeningweekend      7731.0
22606  grossopeningweekend   2031678.0
22607  grossopeningweekend         NaN

[22608 rows x 2 columns]

In [40]:
table = table.reset_index()
table.to_csv('rating_pivot_pais_decada.csv', columns=['decade', 'countryorigin', 'ratingimdb'], index=False, sep=',', encoding='utf-8', na_rep='')